### ISSUE TITLE
github pages

### ISSUE THREAD

**Issue by thorade** [yoavram/hello-citeproc#1]
Might be nice to use github pages to display that single simple webpage you built:
https://pages.github.com/

**Comment by yoavram** [comment]
Good idea! Would you like me to make you a collaborator so that you can do it?

**Comment by thorade** [comment]
Sure, you can do that. 
All I'll do is create a new branch `gh-pages` that is identical to the `master` and then make that the defautl branch. And add a link in the Readme.

**Comment by yoavram** [comment]
Sounds good. Go ahead!

**Comment by thorade** [comment]
Done. You can now remove me as a collaborator.
Changig the default branch can be done by the repo owner  only.
Not sure, maybe the master branch can even be deleted once the gh-pages branch is the default.

**Comment by yoavram** [comment]
I'll have a look.

**Comment by yoavram** [comment]
I think you need to create an index.HTML?

**Comment by thorade** [comment]
Or you can use the full address:
http://yoavram.github.io/hello-citeproc/hello-citeproc.html
That is the link I added to the ReadMe

**Comment by yoavram** [comment]
Right. 
I made `gh-pages` the default branch.
The site doesn't work though - I get `GET http://yoavram.github.io/hello-citeproc/helloword-citeproc.js 404 (Not Found)` in the console, any idea why?

**Comment by thorade** [comment]
http://yoavram.github.io/hello-citeproc/helloword-citeproc.js (404)
http://yoavram.github.io/hello-citeproc/hello-citeproc.js (works)

remove the word `word`

**Comment by thorade** [comment]
I was now able to delete the `master` branch, 
so now there is only one branch `gh-pages` and it is no longer necessary to sync branches.

**Comment by yoavram** [comment]
I fixed the ref to the js file.

**Comment by thorade** [comment]
Thanks
